# Generated by Django 5.0.2 on 2024-02-21 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25)),
                ('type', models.TextField(default=None)),
                ('description', models.TextField(max_length=255)),
                ('deadline', models.DateTimeField(default=datetime.date.today)),
                ('who_created', models.TextField(default=None)),
                ('status', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField()),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('surname', models.TextField(default=None)),
                ('tg_id', models.TextField(unique=True)),
                ('course', models.IntegerField(default=None)),
                ('group', models.IntegerField(default=None)),
                ('type', models.TextField(default=None)),
                ('admin', models.BooleanField(default=False)),
                ('superadmin', models.BooleanField(default=False)),
            ],
        ),
    ]
