# Generated by Django 5.0.2 on 2024-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_superadmin_remove_taskuser_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_id',
            field=models.IntegerField(default=None),
        ),
    ]
